In [14]:
# import dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [15]:
# import sklearn dependencies
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from imblearn.metrics import classification_report_imbalanced

In [16]:
# load the data
merged_df = pd.read_csv("merged_df.csv", index_col=[0],sep=',')
merged_df.head()

GeoFips      county  pcp_count  population  pop_density  per_capita_income  \
0    12086  Miami-Dade      13619     2715516   552.187071              57213   
1     6025    Imperial        236      180216    16.659991              44500   
2    40109    Oklahoma       2914      782051   425.989528              56971   
3    39115      Morgan         19       14702    13.631412              38583   
4     8059   Jefferson       1459      570427   288.167016              68829   

   pcp_per_capita  pop_density_lvl  region_Far West  region_Great Lakes  ...  \
0        5.015253                3                0                   0  ...   
1        1.309540                1                1                   0  ...   
2        3.726100                3                0                   0  ...   
3        1.292341                1                0                   1  ...   
4        2.557733                3                0                   0  ...   

   state_TN  state_TX  state_UT  state_VA  state_VT  state_WA  state_WI  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   state_WV  state_WY  pcp_per_capita_bins  
0         0         0                    1  
1         0         0                    1  
2         0         0                    1  
3         0         0                    1  
4         0         0                    1  

[5 rows x 68 columns]

GeoFips      county  pcp_count  population  pop_density  per_capita_income  \
0    12086  Miami-Dade      13619     2715516   552.187071              57213   
1     6025    Imperial        236      180216    16.659991              44500   
2    40109    Oklahoma       2914      782051   425.989528              56971   
3    39115      Morgan         19       14702    13.631412              38583   
4     8059   Jefferson       1459      570427   288.167016              68829   

   pcp_per_capita  pop_density_lvl  region_Far West  region_Great Lakes  ...  \
0        5.015253                3                0                   0  ...   
1        1.309540                1                1                   0  ...   
2        3.726100                3                0                   0  ...   
3        1.292341                1                0                   1  ...   
4        2.557733                3                0                   0  ...   

   state_TN  state_TX  state_UT  state_VA  state_VT  state_WA  state_WI  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   state_WV  state_WY  pcp_per_capita_bins  
0         0         0                    1  
1         0         0                    1  
2         0         0                    1  
3         0         0                    1  
4         0         0                    1  

[5 rows x 68 columns]

In [17]:
# Create features
X = merged_df.drop(columns=["pcp_per_capita", "pcp_per_capita_bins", "pop_density", "per_capita_income", "state_AK", "state_AL", "state_AR", "state_AZ", "state_CA", "state_CO",
"state_CT", "state_DC", "state_DE", "state_FL", "state_GA", "state_HI",
"state_IA", "state_ID", "state_IL", "state_IN", "state_KS", "state_KY",
"state_LA", "state_MA", "state_MD", "state_ME", "state_MI", "state_MN",
"state_MO", "state_MS", "state_MT", "state_NC", "state_ND", "state_NE",
"state_NH", "state_NJ", "state_NM", "state_NV", "state_NY", "state_OH",
"state_OK", "state_OR", "state_PA", "state_RI", "state_SC", "state_SD",
"state_TN", "state_TX", "state_UT", "state_VA", "state_VT", "state_WA",
"state_WI", "state_WV", "state_WY"])
X = pd.get_dummies(X) 

# Create target
y = merged_df["pcp_per_capita_bins"]

In [18]:
X.describe()

GeoFips     pcp_count    population  pop_density_lvl  \
count   3029.000000   3029.000000  3.029000e+03      3029.000000   
mean   29981.758666    339.705513  1.141870e+05         1.496864   
std    15070.955336   1094.505146  4.231330e+05         1.118362   
min     1001.000000      1.000000  4.590000e+02         0.000000   
25%    18153.000000     18.000000  1.196200e+04         0.000000   
50%    29095.000000     56.000000  2.721600e+04         1.000000   
75%    44001.000000    198.000000  7.152200e+04         2.000000   
max    56045.000000  18526.000000  1.009805e+07         3.000000   

       region_Far West  region_Great Lakes  region_Mideast  \
count      3029.000000         3029.000000     3029.000000   
mean          0.059756            0.144272        0.059426   
std           0.237073            0.351423        0.236458   
min           0.000000            0.000000        0.000000   
25%           0.000000            0.000000        0.000000   
50%           0.000000            0.000000        0.000000   
75%           0.000000            0.000000        0.000000   
max           1.000000            1.000000        1.000000   

       region_New England  region_Plains  region_Rocky Mountain  ...  \
count         3029.000000    3029.000000            3029.000000  ...   
mean             0.022450       0.193793               0.067019  ...   
std              0.148165       0.395334               0.250096  ...   
min              0.000000       0.000000               0.000000  ...   
25%              0.000000       0.000000               0.000000  ...   
50%              0.000000       0.000000               0.000000  ...   
75%              0.000000       0.000000               0.000000  ...   
max              1.000000       1.000000               1.000000  ...   

       county_Yellowstone  county_Yoakum  county_Yolo  county_York  \
count          3029.00000     3029.00000   3029.00000  3029.000000   
mean              0.00033        0.00033      0.00033     0.001321   
std               0.01817        0.01817      0.01817     0.036322   
min               0.00000        0.00000      0.00000     0.000000   
25%               0.00000        0.00000      0.00000     0.000000   
50%               0.00000        0.00000      0.00000     0.000000   
75%               0.00000        0.00000      0.00000     0.000000   
max               1.00000        1.00000      1.00000     1.000000   

       county_Young  county_Yuba  county_Yukon-Koyukuk  county_Yuma  \
count    3029.00000   3029.00000            3029.00000  3029.000000   
mean        0.00033      0.00033               0.00033     0.000660   
std         0.01817      0.01817               0.01817     0.025692   
min         0.00000      0.00000               0.00000     0.000000   
25%         0.00000      0.00000               0.00000     0.000000   
50%         0.00000      0.00000               0.00000     0.000000   
75%         0.00000      0.00000               0.00000     0.000000   
max         1.00000      1.00000               1.00000     1.000000   

       county_Zapata  county_Zavala  
count     3029.00000     3029.00000  
mean         0.00033        0.00033  
std          0.01817        0.01817  
min          0.00000        0.00000  
25%          0.00000        0.00000  
50%          0.00000        0.00000  
75%          0.00000        0.00000  
max          1.00000        1.00000  

[8 rows x 1760 columns]

GeoFips     pcp_count    population  pop_density_lvl  \
count   3029.000000   3029.000000  3.029000e+03      3029.000000   
mean   29981.758666    339.705513  1.141870e+05         1.496864   
std    15070.955336   1094.505146  4.231330e+05         1.118362   
min     1001.000000      1.000000  4.590000e+02         0.000000   
25%    18153.000000     18.000000  1.196200e+04         0.000000   
50%    29095.000000     56.000000  2.721600e+04         1.000000   
75%    44001.000000    198.000000  7.152200e+04         2.000000   
max    56045.000000  18526.000000  1.009805e+07         3.000000   

       region_Far West  region_Great Lakes  region_Mideast  \
count      3029.000000         3029.000000     3029.000000   
mean          0.059756            0.144272        0.059426   
std           0.237073            0.351423        0.236458   
min           0.000000            0.000000        0.000000   
25%           0.000000            0.000000        0.000000   
50%           0.000000            0.000000        0.000000   
75%           0.000000            0.000000        0.000000   
max           1.000000            1.000000        1.000000   

       region_New England  region_Plains  region_Rocky Mountain  ...  \
count         3029.000000    3029.000000            3029.000000  ...   
mean             0.022450       0.193793               0.067019  ...   
std              0.148165       0.395334               0.250096  ...   
min              0.000000       0.000000               0.000000  ...   
25%              0.000000       0.000000               0.000000  ...   
50%              0.000000       0.000000               0.000000  ...   
75%              0.000000       0.000000               0.000000  ...   
max              1.000000       1.000000               1.000000  ...   

       county_Yellowstone  county_Yoakum  county_Yolo  county_York  \
count          3029.00000     3029.00000   3029.00000  3029.000000   
mean              0.00033        0.00033      0.00033     0.001321   
std               0.01817        0.01817      0.01817     0.036322   
min               0.00000        0.00000      0.00000     0.000000   
25%               0.00000        0.00000      0.00000     0.000000   
50%               0.00000        0.00000      0.00000     0.000000   
75%               0.00000        0.00000      0.00000     0.000000   
max               1.00000        1.00000      1.00000     1.000000   

       county_Young  county_Yuba  county_Yukon-Koyukuk  county_Yuma  \
count    3029.00000   3029.00000            3029.00000  3029.000000   
mean        0.00033      0.00033               0.00033     0.000660   
std         0.01817      0.01817               0.01817     0.025692   
min         0.00000      0.00000               0.00000     0.000000   
25%         0.00000      0.00000               0.00000     0.000000   
50%         0.00000      0.00000               0.00000     0.000000   
75%         0.00000      0.00000               0.00000     0.000000   
max         1.00000      1.00000               1.00000     1.000000   

       county_Zapata  county_Zavala  
count     3029.00000     3029.00000  
mean         0.00033        0.00033  
std          0.01817        0.01817  
min          0.00000        0.00000  
25%          0.00000        0.00000  
50%          0.00000        0.00000  
75%          0.00000        0.00000  
max          1.00000        1.00000  

[8 rows x 1760 columns]

In [19]:
# Check the balance of our target values
y.value_counts()

1    2881
0     148
Name: pcp_per_capita_bins, dtype: int64

1    2881
0     148
Name: pcp_per_capita_bins, dtype: int64

In [20]:
# Train, test, split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
    y, random_state=1)

In [21]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
random_forest = BalancedRandomForestClassifier(n_estimators = 100)
random_forest = random_forest.fit(X_train, y_train)

In [22]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = random_forest.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.908230419239519

0.908230419239519

In [23]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 31   3]
 [ 69 655]]
[[ 31   3]
 [ 69 655]]


In [24]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.31      0.91      0.90      0.46      0.91      0.83        34
          1       1.00      0.90      0.91      0.95      0.91      0.82       724

avg / total       0.96      0.91      0.91      0.93      0.91      0.82       758

                   pre       rec       spe        f1       geo       iba       sup

          0       0.31      0.91      0.90      0.46      0.91      0.83        34
          1       1.00      0.90      0.91      0.95      0.91      0.82       724

avg / total       0.96      0.91      0.91      0.93      0.91      0.82       758



In [25]:
# List the features sorted in descending order by feature importance
feature_names = X.columns
sorted(zip(random_forest.feature_importances_, feature_names), reverse=True)

[(0.3579915653747901, 'pcp_count'),
 (0.17517299037918277, 'population'),
 (0.06466228298342844, 'GeoFips'),
 (0.05129256564212864, 'pop_density_lvl'),
 (0.012369037184989565, 'region_Southeast'),
 (0.007735871933347174, 'region_Rocky Mountain'),
 (0.007471946511600442, 'region_Plains'),
 (0.006049277187512302, 'region_Far West'),
 (0.005499866584241567, 'region_Southwest'),
 (0.005145980420641363, 'region_Mideast'),
 (0.004572959904752935, 'region_Great Lakes'),
 (0.0035399121199545646, 'county_Jefferson'),
 (0.0033221910336043666, 'county_Cass'),
 (0.003265422770929177, 'region_New England'),
 (0.003247423431408616, 'county_Calumet'),
 (0.00265458958228761, 'county_Harris'),
 (0.002597147769073972, 'county_Upshur'),
 (0.002569810669515998, 'county_Benton'),
 (0.002501874480003684, 'county_Macon'),
 (0.0023562743356298054, 'county_Hart'),
 (0.002311117184697795, 'county_Posey'),
 (0.002090548717674469, 'county_Greene'),
 (0.002017866945358578, 'county_Monroe'),
 (0.0020119236074613196

[(0.3579915653747901, 'pcp_count'),
 (0.17517299037918277, 'population'),
 (0.06466228298342844, 'GeoFips'),
 (0.05129256564212864, 'pop_density_lvl'),
 (0.012369037184989565, 'region_Southeast'),
 (0.007735871933347174, 'region_Rocky Mountain'),
 (0.007471946511600442, 'region_Plains'),
 (0.006049277187512302, 'region_Far West'),
 (0.005499866584241567, 'region_Southwest'),
 (0.005145980420641363, 'region_Mideast'),
 (0.004572959904752935, 'region_Great Lakes'),
 (0.0035399121199545646, 'county_Jefferson'),
 (0.0033221910336043666, 'county_Cass'),
 (0.003265422770929177, 'region_New England'),
 (0.003247423431408616, 'county_Calumet'),
 (0.00265458958228761, 'county_Harris'),
 (0.002597147769073972, 'county_Upshur'),
 (0.002569810669515998, 'county_Benton'),
 (0.002501874480003684, 'county_Macon'),
 (0.0023562743356298054, 'county_Hart'),
 (0.002311117184697795, 'county_Posey'),
 (0.002090548717674469, 'county_Greene'),
 (0.002017866945358578, 'county_Monroe'),
 (0.0020119236074613196

In [26]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
easy = EasyEnsembleClassifier(n_estimators = 100,random_state=1)
easy = easy.fit(X_train, y_train)

In [27]:
# Calculated the balanced accuracy score
y_pred = easy.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.96250406239844

0.96250406239844

In [28]:
# Display the confusion matrix
y_pred = easy.predict(X_test)
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 33   1]
 [ 33 691]]
[[ 33   1]
 [ 33 691]]


In [29]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.50      0.97      0.95      0.66      0.96      0.93        34
          1       1.00      0.95      0.97      0.98      0.96      0.92       724

avg / total       0.98      0.96      0.97      0.96      0.96      0.92       758

                   pre       rec       spe        f1       geo       iba       sup

          0       0.50      0.97      0.95      0.66      0.96      0.93        34
          1       1.00      0.95      0.97      0.98      0.96      0.92       724

avg / total       0.98      0.96      0.97      0.96      0.96      0.92       758



In [30]:
# find r-squared score
r2_score(y_test, y_pred)

-0.04696132596685065

-0.04696132596685065